apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi-deployment

spec:
  replicas:
  selectors:
    matchLabels:
      app: myapi
  template:
    metadata:
      labels:
        app: myapi
    spec:
      containers:
      - name: kings5layer/myapi:latest