apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi-deployment

spec:
  replicas: 3
  selectors:
    matchLabels:
      app: myapi
  template:
    metadata:
      labels:
        app: myapi
    spec:
      containers:
        - name: myapi
          imagePullPolicy: Always
          image: kings5layer/myapi:0.0.1

          resources:
            limits:
              memory: "200Mi"
              cpu: "200m"

          ports:
            - containerPort: 8888
              name: myapi-svc

          livenessProbe:
            httpGet:
              path: /health
              port: 8888
              initialDelaySeconds: 3
              periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8888
              initialDelaySeconds: 3
              periodSeconds: 3
